# https://nbsoftsolutions.com/blog/azure-pipelines-for-rust-projects
strategy:
  matrix:
    windows-stable:
      imageName: 'vs2017-win2016'
      rustup_toolchain: stable
    mac-stable:
      imageName: 'macos-10.13'
      rustup_toolchain: stable
    linux-stable:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: stable
    linux-beta:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: beta
    linux-nightly:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: nightly

pool:
  vmImage: $(imageName)

steps:
  - bash: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Windows install rust
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - bash: cargo build --all
    displayName: Cargo build
  - bash: cargo test --all
    displayName: Cargo test

  - bash: |
      cargo build -p cgenie-drs --release
      cargo build -p cgenie-hki --release
      cargo build -p cgenie-lang --release
      cargo build -p cgenie-scx --release
      cargo build -p cgenie --release
      mkdir -p artifact-64bit/libs/
      cp -R c/include artifact-64bit/
      cp target/release/*.dll artifact-64bit/libs/
      cp target/release/*.lib artifact-64bit/libs/
    displayName: Prepare 64 bit C API libraries
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - publish: artifact-64bit
    artifact: cgenie-x64
    condition: eq( variables['Agent.OS'], 'Windows_NT' )

  - bash: |
      rustup toolchain install stable-i686-pc-windows-msvc
      cargo build +stable-i686-pc-windows-msvc -p cgenie-drs --release
      cargo build +stable-i686-pc-windows-msvc -p cgenie-hki --release
      cargo build +stable-i686-pc-windows-msvc -p cgenie-lang --release
      cargo build +stable-i686-pc-windows-msvc -p cgenie-scx --release
      cargo build +stable-i686-pc-windows-msvc -p cgenie --release
      mkdir -p artifact-32bit/libs/
      cp -R c/include artifact-32bit/
      cp target/i686-pc-windows-msvc/release/*.dll artifact-32bit/libs/
      cp target/i686-pc-windows-msvc/release/*.lib artifact-32bit/libs/
    displayName: Prepare 32 bit C API libraries
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - publish: artifact-32bit
    artifact: cgenie-x86
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
