[package]
name = "genie-rec"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
arrayvec = "0.5"
byteorder = "^1.3.1"
flate2 = { version = "^1.0.0", features = ["rust_backend"], default-features = false }
genie-scx = { version = "2.0.0", path = "../genie-scx" }
genie-support = { version = "0.0.0", path = "../genie-support" }
