[package]
name = "genie-rec"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"
license = "GPL-3.0"
description = "Read Age of Empires I/II recorded game files."
homepage = "https://github.com/SiegeEngineers/genie-rs"
repository = "https://github.com/SiegeEngineers/genie-rs"

[dependencies]
arrayvec = "0.5"
byteorder = "^1.3.1"
flate2 = { version = "^1.0.0", features = ["rust_backend"], default-features = false }
genie-dat = { version = "0.1.0", path = "../genie-dat" }
genie-scx = { version = "3.0.0", path = "../genie-scx" }
genie-support = { version = "1.0.0", path = "../genie-support", features = ["strings"] }
thiserror = "1.0.13"

[dev-dependencies]
anyhow = "1.0.27"
