[package]
name = "genie-rec"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
auto-serializer = { path = "../auto-serializer" }
byteorder = "^1.3.1"
flate2 = { version = "^1.0.0", features = ["rust_backend"], default-features = false }
genie-scx = { version = "1.0.0", path = "../genie-scx" }
