[package]
name = "genie-dat"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
arraystring = "^0.3.0"
byteorder = "^1.3.1"
flate2 = { version = "^1.0.0", features = ["rust_backend"], default-features = false }
