[package]
name = "genie-scx"
version = "2.0.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"
license = "GPL-3.0"
description = "Read and write Age of Empires I/II scenario files."
homepage = "https://github.com/SiegeEngineers/genie-rs"
repository = "https://github.com/SiegeEngineers/genie-rs"

[dependencies]
byteorder = "^1.3.1"
encoding_rs = "^0.8.17"
flate2 = "^1.0.0"
num-derive = "^0.2.0"
num-traits = "^0.2.0"
