[package]
name = "genie-scx"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
byteorder = "^1.3.1"
encoding_rs = "^0.8.17"
flate2 = { version = "^1.0.0", features = ["rust_backend"], default-features = false }
num-derive = "^0.2.0"
num-traits = "^0.2.0"
quicli = "^0.4.0"
structopt = "^0.2.0"
