[package]
name = "genie-slp"
version = "0.0.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
byteorder = "^1.3.1"
jascpal = { version = "0.1.1", path = "../jascpal" }
rgb = "0.8.17"

[dev-dependencies]
anyhow = "1.0.31"
